### ISSUE TITLE
Line Style Builder login

### ISSUE THREAD

**Issue by MikusRL** [iho-ohi/S100Infrastructure#11]
The Line style builder app is asking for yet another login. S100 Toolkits login is not working for this. When pressing the "join" button it leads to initial user access request page at GI Registry. Is there another level of testing still going on for the line style builder and it is not yet opened for general GI Registry and Toolkit users? Thanks.
![image](https://github.com/iho-ohi/S100Infrastructure/assets/72803214/35a1fd84-3591-4dc1-9117-6884520ab614)

**Comment by gorogara** [comment]
@MikusRL 
LineStyleBuilder has been changed to LinePatternEditor.
LinePatternEditor supports editing of Line and Area on single system.
There is no need for a login process because you log in from the launcher.
Please try again, and if there are no problems, please close the issue.
![image](https://github.com/iho-ohi/S100Infrastructure/assets/5345308/97c71870-b0ea-4cae-b869-c98bd3e4e63e)
![image](https://github.com/iho-ohi/S100Infrastructure/assets/5345308/7e68e98a-a145-4eaf-8178-b7af810f9065)

**Comment by iho-ohi** [comment]
It's been solved.
